name: sliver_stretch_header
description: Flutter implementation of stretchable header with a background as a sliver. Use it in a CustomScrollView.
version: 0.1.0
homepage: https://github.com/ShannonChenCHN/sliver_stretch_header

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter