name: sliver_stretchy_header
description: A sliver that contains a bottom-aligned box child and a stretchy box background. Use it in a CustomScrollView.
version: 0.2.0
homepage: https://github.com/ShannonChenCHN/sliver_stretchy_header

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter